/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sirh;

import controller.ControllerKamar;
import controller.ControllerReservasi;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author usernames
 */
public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    String[] operatorLogin = {"operator1", "perator2"};
    
    ControllerReservasi controllerReservasi;
    ControllerKamar controllerKamar;
    
    public Operator() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        pack();
    }         
    
    
    /** PANEL KAMAR **/
    
    public JTable getKamarTableData(){
        return tblRoom;
    }
    
    public JButton getBtnKamarInsert(){
        return btnInsertRoom;
    }
    
    public JButton getBtnKamarUpdate(){
        return btnUpdateRoom;
    }
    
    public JButton getBtnKamarDelete(){
        return btnDeleteRoom;
    }  
    
        
    
    /** PANEL ADD KAMAR **/
    
    public JSpinner getSpIdKamarAdd(){
        return spIdKamarAdd;
    }
    
    public JSpinner getSpNoKamarAdd(){
        return spNoKamarAdd;
    }
    
    public JComboBox getCbTipeKamarAdd(){
        return cbTipeKamarAdd;
    }
    
    public JComboBox getCbStatusKamarAdd(){
        return cbStatusKamarAdd;
    }
    
    
    /** PANEL UPDATE KAMAR **/
    
    public JSpinner getSpIdKamarUpdate(){
        return spIdKamarUpdate;
    }
    
    public JSpinner getSpNoKamarUpdate(){
        return spNoKamarUpdate;
    }
    
    public JComboBox getCbTipeKamarUpdate(){
        return cbTipeKamarUpdate;
    }
    
    public JComboBox getCbStatusKamarUpdate(){
        return cbStatusKamarUpdate;
    }
        
    
    /** PANEL TIPE KAMAR **/
    
    public JTable getTipeKamarTableData(){
        return tblRoomType;
    }
    
    public JButton getBtnInsertKamarType(){
        return btnInsertRoomType;
    }
    
    public JButton getBtnDeleteKamarType(){
        return btnDeleteRoomType;
    }
    
    public JButton getBtnUpdateKamarType(){
        return btnUpdateRoomType;
    }
    
    
    /**PANEL ADD TIPE KAMAR**/
    
    public JSpinner getSpIdTipeKamarAdd(){
        return spIdTipeKamarAdd;
    }
    
    public JTextField getTfNamaTipeKamarAdd(){
        return tfNamaTipeKamarAdd;
    }
    
    public JTextField getTfHargaTipeKamarAdd(){
        return tfHargaTipeKamarAdd;
    }
    
    
    /**PANEL UPDATE TIPE KAMAR**/
    
     public JSpinner getSpIdTipeKamarUpdate(){
        return spIdTipeKamarUpdate;
    }
    
    public JTextField getTfNamaTipeKamarUpdate(){
        return tfNamaTipeKamarUpdate;
    }
    
    public JTextField getTfHargaTipeKamarUpdate(){
        return tfHargaTipeKamarUpdate;
    }
    
    
    /** PANEL RESERVATION **/
    
    public JTable getResTableData(){
        return tblRes;
    }
    
//    public JButton getResBtnInsert(){
//        return btnInsertReser;
//    }
//    
    public JButton getResBtnUpdate(){
        return btnUpdateReser;
    }
    
    public JButton getResBtnDelete(){
        return btnDeleteReser;
    }
    
    
    /** PANEL UPDATE RESERVASI **/
    
    public JLabel getLblIdResUpdate(){
        return lblIdResUpdate;
    }
    
    public JLabel getLblIdGuestResUpdate(){
        return lblIdGuestResUpdate;
    }
    
    public JLabel getLblSpecialOrderResUpdate(){
        return lblSpecialOrderResUpdate;
    }
    
    public JLabel getLblCheckInResUpdate(){
        return lblCheckInResUpdate;
    }
    
    public JLabel getLblCheckOutResUpdate(){
        return lblCheckOutResUpdate;
    }
    
    public JLabel getLblDiskonResUpdate(){
        return lblDiskonResUpdate;
    }
    
    public JLabel getLblPriceResUpdate(){
        return lblPriceResUpdate;
    }
    
    public JLabel getLblTotPriceResUpdate(){
        return lblTotPriceResUpdate;
    }

    public JComboBox getCbStatusResUpdate(){
        return cbStatusResUpdate;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panel1 = new usu.widget.Panel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel2 = new javax.swing.JLabel();
        panelLoginForm = new usu.widget.Panel();
        tfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        panel2 = new usu.widget.Panel();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        btnReviewReports = new javax.swing.JButton();
        btnManageRoom = new javax.swing.JButton();
        btnManageReser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelRoom = new usu.widget.Panel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        jLabel5 = new javax.swing.JLabel();
        panelIcon = new usu.widget.Panel();
        btnUpdateRoom = new javax.swing.JButton();
        btnInsertRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        panelTabelRoom = new usu.widget.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoom = new javax.swing.JTable();
        btnBackRoom = new javax.swing.JButton();
        panelRoomAdd = new usu.widget.Panel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jLabel9 = new javax.swing.JLabel();
        btnBackRoomAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbStatusKamarAdd = new javax.swing.JComboBox<>();
        cbTipeKamarAdd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spNoKamarAdd = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSubmitAddKamar = new javax.swing.JButton();
        spIdKamarAdd = new javax.swing.JSpinner();
        panelRoomUpdate = new usu.widget.Panel();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        btnBackRoomUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbStatusKamarUpdate = new javax.swing.JComboBox<>();
        cbTipeKamarUpdate = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        spNoKamarUpdate = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        spIdKamarUpdate = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        panelRoomType = new usu.widget.Panel();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        btnBackRoomType = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panelTabelRoom1 = new usu.widget.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRoomType = new javax.swing.JTable();
        panelIcon2 = new usu.widget.Panel();
        btnUpdateRoomType = new javax.swing.JButton();
        btnInsertRoomType = new javax.swing.JButton();
        btnDeleteRoomType = new javax.swing.JButton();
        panelRoomTypeAdd = new usu.widget.Panel();
        panelGlass9 = new usu.widget.glass.PanelGlass();
        jLabel10 = new javax.swing.JLabel();
        btnBackRoomTypeAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSubmitAddTipeKamar = new javax.swing.JButton();
        spIdTipeKamarAdd = new javax.swing.JSpinner();
        tfHargaTipeKamarAdd = new javax.swing.JTextField();
        tfNamaTipeKamarAdd = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        panelRoomTypeUpdate = new usu.widget.Panel();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        jLabel22 = new javax.swing.JLabel();
        btnBackRoomTypeUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnSubmitUpdateTipeKamar = new javax.swing.JButton();
        spIdTipeKamarUpdate = new javax.swing.JSpinner();
        tfHargaTipeKamarUpdate = new javax.swing.JTextField();
        tfNamaTipeKamarUpdate = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        panelReservation = new usu.widget.Panel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jLabel7 = new javax.swing.JLabel();
        panelIcon1 = new usu.widget.Panel();
        btnUpdateReser = new javax.swing.JButton();
        btnDeleteReser = new javax.swing.JButton();
        btnRefreshReser = new javax.swing.JButton();
        panelTabelReser = new usu.widget.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRes = new javax.swing.JTable();
        btnBackReser = new javax.swing.JButton();
        panelReservationUpdate = new usu.widget.Panel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        btnBackReser1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblCheckInResUpdate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnUpdateSubmitRes = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblIdResUpdate = new javax.swing.JLabel();
        lblDiskonResUpdate = new javax.swing.JLabel();
        lblCheckOutResUpdate = new javax.swing.JLabel();
        lblSpecialOrderResUpdate = new javax.swing.JLabel();
        lblIdGuestResUpdate = new javax.swing.JLabel();
        cbStatusResUpdate = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        lblTotPriceResUpdate = new javax.swing.JLabel();
        lblPriceResUpdate = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider1.setOpaque(false);

        panel1.setOpaque(false);
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setAlpha(0.9F);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoDamaiHotel.resized.png"))); // NOI18N

        panelLoginForm.setOpaque(false);
        panelLoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelLoginForm.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 280, 40));

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        panelLoginForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        panelLoginForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        panelLoginForm.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, 40));

        btnLogin.setBackground(new java.awt.Color(218, 151, 69));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(186, 186, 186))
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(panelLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(panelLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        panel1.add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 590, 380));

        jPanelSlider1.add(panel1, "card2");

        panel2.setOpaque(false);
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass2.setAlpha(0.6F);
        panelGlass2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReviewReports.setBackground(new java.awt.Color(218, 151, 69));
        btnReviewReports.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btnReviewReports.setText("Review Reports");
        panelGlass2.add(btnReviewReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 340, 60));

        btnManageRoom.setBackground(new java.awt.Color(218, 151, 69));
        btnManageRoom.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btnManageRoom.setText("Manage Room");
        btnManageRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRoomActionPerformed(evt);
            }
        });
        panelGlass2.add(btnManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 340, 60));

        btnManageReser.setBackground(new java.awt.Color(218, 151, 69));
        btnManageReser.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        btnManageReser.setText("Manage Reservation");
        btnManageReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReserActionPerformed(evt);
            }
        });
        panelGlass2.add(btnManageReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 340, 60));

        btnLogout.setBackground(new java.awt.Color(203, 62, 61));
        btnLogout.setForeground(new java.awt.Color(254, 254, 254));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panelGlass2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 100, -1));

        panel2.add(panelGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 510, 420));

        jPanelSlider1.add(panel2, "card3");

        panelRoom.setOpaque(false);

        panelGlass3.setAlpha(0.9F);
        panelGlass3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("STIXGeneral", 0, 36)); // NOI18N
        jLabel5.setText("Room Management");
        panelGlass3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        panelIcon.setOpaque(false);
        panelIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-update35.png"))); // NOI18N
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });
        panelIcon.add(btnUpdateRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 50, 50));

        btnInsertRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-add35.png"))); // NOI18N
        btnInsertRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRoomActionPerformed(evt);
            }
        });
        panelIcon.add(btnInsertRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 50, 50));

        btnDeleteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-delete35.png"))); // NOI18N
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });
        panelIcon.add(btnDeleteRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 50, 50));

        panelGlass3.add(panelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 790, 70));

        panelTabelRoom.setOpaque(false);

        tblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room No.", "Room Id.", "Room Type", "Room Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRoom);

        javax.swing.GroupLayout panelTabelRoomLayout = new javax.swing.GroupLayout(panelTabelRoom);
        panelTabelRoom.setLayout(panelTabelRoomLayout);
        panelTabelRoomLayout.setHorizontalGroup(
            panelTabelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelRoomLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        panelTabelRoomLayout.setVerticalGroup(
            panelTabelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelRoomLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass3.add(panelTabelRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 790, 300));

        btnBackRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoom.setText("Back");
        btnBackRoom.setIconTextGap(6);
        btnBackRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomActionPerformed(evt);
            }
        });
        panelGlass3.add(btnBackRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        javax.swing.GroupLayout panelRoomLayout = new javax.swing.GroupLayout(panelRoom);
        panelRoom.setLayout(panelRoomLayout);
        panelRoomLayout.setHorizontalGroup(
            panelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelRoomLayout.setVerticalGroup(
            panelRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSlider1.add(panelRoom, "card4");

        panelRoomAdd.setOpaque(false);
        panelRoomAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass6.setAlpha(0.9F);
        panelGlass6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel9.setText("ADD ROOM");
        panelGlass6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        btnBackRoomAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoomAdd.setText("Cancel");
        btnBackRoomAdd.setIconTextGap(6);
        btnBackRoomAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomAddActionPerformed(evt);
            }
        });
        panelGlass6.add(btnBackRoomAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbStatusKamarAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unavailable", "Available" }));
        cbStatusKamarAdd.setSelectedIndex(1);
        jPanel1.add(cbStatusKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        cbTipeKamarAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Presidential" }));
        jPanel1.add(cbTipeKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel15.setText("Status");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel14.setText("Room No.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        spNoKamarAdd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spNoKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 100, 70, -1));

        jLabel16.setText("Type");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel13.setText("Room ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnSubmitAddKamar.setBackground(new java.awt.Color(209, 170, 88));
        btnSubmitAddKamar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnSubmitAddKamar.setForeground(new java.awt.Color(254, 254, 254));
        btnSubmitAddKamar.setText("ADD");
        btnSubmitAddKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAddKamarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitAddKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 78, 51));

        spIdKamarAdd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spIdKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 40, 70, -1));

        panelGlass6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        panelRoomAdd.add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 48, 620, 380));

        jPanelSlider1.add(panelRoomAdd, "card6");

        panelRoomUpdate.setOpaque(false);
        panelRoomUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass7.setAlpha(0.9F);
        panelGlass7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackRoomUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoomUpdate.setText("Cancel");
        btnBackRoomUpdate.setIconTextGap(6);
        btnBackRoomUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomUpdateActionPerformed(evt);
            }
        });
        panelGlass7.add(btnBackRoomUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbStatusKamarUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        jPanel2.add(cbStatusKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        cbTipeKamarUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidential", "Deluxe" }));
        jPanel2.add(cbTipeKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel17.setText("Status");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel18.setText("Room No.");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        spNoKamarUpdate.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel2.add(spNoKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 100, 70, -1));

        jLabel19.setText("Type");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel20.setText("Room ID");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jButton4.setBackground(new java.awt.Color(209, 170, 88));
        jButton4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 51));

        spIdKamarUpdate.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel2.add(spIdKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 40, 70, -1));

        panelGlass7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel11.setText("UPDATE ROOM");
        panelGlass7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        panelRoomUpdate.add(panelGlass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 48, 620, 380));

        jPanelSlider1.add(panelRoomUpdate, "card6");

        panelRoomType.setOpaque(false);
        panelRoomType.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass8.setAlpha(0.9F);
        panelGlass8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoomType.setText("Back");
        btnBackRoomType.setIconTextGap(6);
        btnBackRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomTypeActionPerformed(evt);
            }
        });
        panelGlass8.add(btnBackRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("STIXGeneral", 0, 36)); // NOI18N
        jLabel12.setText("Room Type");
        panelGlass8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        panelTabelRoom1.setOpaque(false);

        tblRoomType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type ID", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRoomType);

        javax.swing.GroupLayout panelTabelRoom1Layout = new javax.swing.GroupLayout(panelTabelRoom1);
        panelTabelRoom1.setLayout(panelTabelRoom1Layout);
        panelTabelRoom1Layout.setHorizontalGroup(
            panelTabelRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelRoom1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        panelTabelRoom1Layout.setVerticalGroup(
            panelTabelRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelRoom1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelGlass8.add(panelTabelRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 570, 300));

        panelIcon2.setOpaque(false);
        panelIcon2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-update35.png"))); // NOI18N
        btnUpdateRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomTypeActionPerformed(evt);
            }
        });
        panelIcon2.add(btnUpdateRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 50, 50));

        btnInsertRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-add35.png"))); // NOI18N
        btnInsertRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRoomTypeActionPerformed(evt);
            }
        });
        panelIcon2.add(btnInsertRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 50));

        btnDeleteRoomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-delete35.png"))); // NOI18N
        btnDeleteRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomTypeActionPerformed(evt);
            }
        });
        panelIcon2.add(btnDeleteRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 50));

        panelGlass8.add(panelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 570, 70));

        panelRoomType.add(panelGlass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 48, 620, 450));

        jPanelSlider1.add(panelRoomType, "card9");

        panelRoomTypeAdd.setOpaque(false);

        panelGlass9.setAlpha(0.9F);
        panelGlass9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel10.setText("ADD ROOM TYPE");
        panelGlass9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        btnBackRoomTypeAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoomTypeAdd.setText("Cancel");
        btnBackRoomTypeAdd.setIconTextGap(6);
        btnBackRoomTypeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomTypeAddActionPerformed(evt);
            }
        });
        panelGlass9.add(btnBackRoomTypeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Name");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setText("Insert number without formatting");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel33.setText("Type ID");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnSubmitAddTipeKamar.setBackground(new java.awt.Color(209, 170, 88));
        btnSubmitAddTipeKamar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnSubmitAddTipeKamar.setForeground(new java.awt.Color(254, 254, 254));
        btnSubmitAddTipeKamar.setText("ADD");
        btnSubmitAddTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAddTipeKamarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSubmitAddTipeKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 78, 51));

        spIdTipeKamarAdd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel3.add(spIdTipeKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, 20));

        tfHargaTipeKamarAdd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(tfHargaTipeKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, -1));
        jPanel3.add(tfNamaTipeKamarAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));

        jLabel34.setText("Price");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        panelGlass9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        javax.swing.GroupLayout panelRoomTypeAddLayout = new javax.swing.GroupLayout(panelRoomTypeAdd);
        panelRoomTypeAdd.setLayout(panelRoomTypeAddLayout);
        panelRoomTypeAddLayout.setHorizontalGroup(
            panelRoomTypeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomTypeAddLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGlass9, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRoomTypeAddLayout.setVerticalGroup(
            panelRoomTypeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomTypeAddLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGlass9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelSlider1.add(panelRoomTypeAdd, "card10");

        panelRoomTypeUpdate.setOpaque(false);

        panelGlass10.setAlpha(0.9F);
        panelGlass10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel22.setText("UPDATE ROOM TYPE");
        panelGlass10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        btnBackRoomTypeUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackRoomTypeUpdate.setText("Cancel");
        btnBackRoomTypeUpdate.setIconTextGap(6);
        btnBackRoomTypeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomTypeUpdateActionPerformed(evt);
            }
        });
        panelGlass10.add(btnBackRoomTypeUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("Name");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel36.setText("Insert number without formatting");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel37.setText("Type ID");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnSubmitUpdateTipeKamar.setBackground(new java.awt.Color(209, 170, 88));
        btnSubmitUpdateTipeKamar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnSubmitUpdateTipeKamar.setForeground(new java.awt.Color(254, 254, 254));
        btnSubmitUpdateTipeKamar.setText("UPDATE");
        btnSubmitUpdateTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitUpdateTipeKamarActionPerformed(evt);
            }
        });
        jPanel4.add(btnSubmitUpdateTipeKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, 51));

        spIdTipeKamarUpdate.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel4.add(spIdTipeKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, 20));

        tfHargaTipeKamarUpdate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(tfHargaTipeKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 150, -1));
        jPanel4.add(tfNamaTipeKamarUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));

        jLabel38.setText("Price");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        panelGlass10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        javax.swing.GroupLayout panelRoomTypeUpdateLayout = new javax.swing.GroupLayout(panelRoomTypeUpdate);
        panelRoomTypeUpdate.setLayout(panelRoomTypeUpdateLayout);
        panelRoomTypeUpdateLayout.setHorizontalGroup(
            panelRoomTypeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomTypeUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRoomTypeUpdateLayout.setVerticalGroup(
            panelRoomTypeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomTypeUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelSlider1.add(panelRoomTypeUpdate, "card11");

        panelReservation.setOpaque(false);

        panelGlass4.setAlpha(0.9F);
        panelGlass4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(218, 151, 69));
        jLabel7.setFont(new java.awt.Font("STIXGeneral", 0, 36)); // NOI18N
        jLabel7.setText("Reservation");
        panelGlass4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        panelIcon1.setOpaque(false);
        panelIcon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-update35.png"))); // NOI18N
        btnUpdateReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReserActionPerformed(evt);
            }
        });
        panelIcon1.add(btnUpdateReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 50, 50));

        btnDeleteReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-delete35.png"))); // NOI18N
        panelIcon1.add(btnDeleteReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 50, 50));

        btnRefreshReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-refresh35.png"))); // NOI18N
        btnRefreshReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshReserActionPerformed(evt);
            }
        });
        panelIcon1.add(btnRefreshReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 50));

        panelGlass4.add(panelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 750, 70));

        panelTabelReser.setOpaque(false);

        tblRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Res. ID", "Guest ID", "Special Order", "Check-In", "Check-Out", "Price", "Disc.", "Total Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRes);

        javax.swing.GroupLayout panelTabelReserLayout = new javax.swing.GroupLayout(panelTabelReser);
        panelTabelReser.setLayout(panelTabelReserLayout);
        panelTabelReserLayout.setHorizontalGroup(
            panelTabelReserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelReserLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        panelTabelReserLayout.setVerticalGroup(
            panelTabelReserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelReserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass4.add(panelTabelReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 790, 280));

        btnBackReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackReser.setText("Back");
        btnBackReser.setIconTextGap(6);
        btnBackReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackReserActionPerformed(evt);
            }
        });
        panelGlass4.add(btnBackReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        javax.swing.GroupLayout panelReservationLayout = new javax.swing.GroupLayout(panelReservation);
        panelReservation.setLayout(panelReservationLayout);
        panelReservationLayout.setHorizontalGroup(
            panelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panelGlass4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(438, 438, 438))
        );
        panelReservationLayout.setVerticalGroup(
            panelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelSlider1.add(panelReservation, "card5");

        panelReservationUpdate.setOpaque(false);

        panelGlass5.setAlpha(0.9F);
        panelGlass5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackReser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/button-previous-32.png"))); // NOI18N
        btnBackReser1.setText("Cancel");
        btnBackReser1.setIconTextGap(6);
        btnBackReser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackReser1ActionPerformed(evt);
            }
        });
        panelGlass5.add(btnBackReser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jLabel6.setFont(new java.awt.Font("STIXGeneral", 0, 24)); // NOI18N
        jLabel6.setText("UPDATE RESERVATION");
        panelGlass5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel21.setText("Res. ID ");
        panelGlass5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblCheckInResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblCheckInResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblCheckInResUpdate.setText("15 Apr, 2016");
        panelGlass5.add(lblCheckInResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel24.setText("Special Order");
        panelGlass5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        btnUpdateSubmitRes.setBackground(new java.awt.Color(209, 170, 88));
        btnUpdateSubmitRes.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnUpdateSubmitRes.setForeground(new java.awt.Color(254, 254, 254));
        btnUpdateSubmitRes.setText("UPDATE");
        btnUpdateSubmitRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSubmitResActionPerformed(evt);
            }
        });
        panelGlass5.add(btnUpdateSubmitRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 100, 51));

        jLabel25.setText("Guest ID");
        panelGlass5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel26.setText("Check-in");
        panelGlass5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel27.setText("Check-out");
        panelGlass5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel28.setText("Diskon");
        panelGlass5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel29.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel29.setText("Status");
        panelGlass5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        lblIdResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblIdResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblIdResUpdate.setText("1");
        panelGlass5.add(lblIdResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        lblDiskonResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblDiskonResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblDiskonResUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiskonResUpdate.setText("5 %");
        panelGlass5.add(lblDiskonResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 40, -1));

        lblCheckOutResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblCheckOutResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblCheckOutResUpdate.setText("16 Apr, 2016");
        panelGlass5.add(lblCheckOutResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblSpecialOrderResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblSpecialOrderResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblSpecialOrderResUpdate.setText("null");
        panelGlass5.add(lblSpecialOrderResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 40, -1));

        lblIdGuestResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblIdGuestResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblIdGuestResUpdate.setText("1");
        panelGlass5.add(lblIdGuestResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        cbStatusResUpdate.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cbStatusResUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unconfirmed", "Confirmed" }));
        panelGlass5.add(cbStatusResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 40));

        jLabel30.setText("Total Price");
        panelGlass5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        lblTotPriceResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblTotPriceResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblTotPriceResUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotPriceResUpdate.setText("2.000.000");
        panelGlass5.add(lblTotPriceResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, -1));

        lblPriceResUpdate.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblPriceResUpdate.setForeground(new java.awt.Color(209, 170, 88));
        lblPriceResUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceResUpdate.setText("2.000.000");
        panelGlass5.add(lblPriceResUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 120, -1));

        jLabel31.setText("Price");
        panelGlass5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        javax.swing.GroupLayout panelReservationUpdateLayout = new javax.swing.GroupLayout(panelReservationUpdate);
        panelReservationUpdate.setLayout(panelReservationUpdateLayout);
        panelReservationUpdateLayout.setHorizontalGroup(
            panelReservationUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationUpdateLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelReservationUpdateLayout.setVerticalGroup(
            panelReservationUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationUpdateLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanelSlider1.add(panelReservationUpdate, "card8");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background-lobby1000.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(920, 530));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 940, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       boolean isOperator = false;
       String username = tfUsername.getText();
       for (int i=0; i<operatorLogin.length; i++){
           if(username.contains(operatorLogin[i])){
               isOperator = true;
               break;
           } else {
               isOperator = false;               
           }
       }      
       if (isOperator){           
            jPanelSlider1.nextPanel(8, panel2, jPanelSlider1.left);
       } else{
           JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        jPanelSlider1.nextPanel(8, panel1, jPanelSlider1.right);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRoomActionPerformed
        controllerKamar = new ControllerKamar(this);
        tblRoom.clearSelection();
        controllerKamar.isiTable();
        jPanelSlider1.nextPanel(8, panelRoom, jPanelSlider1.left); 
    }//GEN-LAST:event_btnManageRoomActionPerformed

    private void btnBackRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomActionPerformed
        jPanelSlider1.nextPanel(8, panel2, jPanelSlider1.right);
    }//GEN-LAST:event_btnBackRoomActionPerformed

    private void btnBackReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackReserActionPerformed
        jPanelSlider1.nextPanel(8, panel2, jPanelSlider1.right);
    }//GEN-LAST:event_btnBackReserActionPerformed

    private void btnManageReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReserActionPerformed
        controllerReservasi = new ControllerReservasi(this);        
        tblRes.clearSelection();
        controllerReservasi.isiTable();
        jPanelSlider1.nextPanel(8, panelReservation, jPanelSlider1.left);        
    }//GEN-LAST:event_btnManageReserActionPerformed

    private void btnInsertRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRoomActionPerformed
        spIdKamarAdd.setValue(controllerKamar.getLastKamarId()+1);
        jPanelSlider1.nextPanel(8, panelRoomAdd, jPanelSlider1.left);
        
    }//GEN-LAST:event_btnInsertRoomActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        int viewRow = tblRoom.getSelectedRow();
        if (viewRow>=0){
            controllerKamar.deleteKamar();
            controllerKamar.isiTable();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row you want to delete");
        }
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed
        int viewRow = tblRoom.getSelectedRow();
        System.out.println(viewRow);
        if(viewRow>=0){            
            spIdKamarUpdate.setValue(tblRoom.getValueAt(viewRow, 0));
            if(tblRoom.getValueAt(viewRow, 1).toString().equalsIgnoreCase("deluxe")){
                cbTipeKamarUpdate.setSelectedIndex(1);
            } else {
                cbTipeKamarUpdate.setSelectedIndex(0);
            }            
            spNoKamarUpdate.setValue(tblRoom.getValueAt(viewRow, 2)); 
            if(tblRoom.getValueAt(viewRow, 3).toString().equalsIgnoreCase("available")){
                cbStatusKamarUpdate.setSelectedIndex(0);
            } else {
                cbStatusKamarUpdate.setSelectedIndex(1);
            }
            jPanelSlider1.nextPanel(8, panelRoomUpdate, jPanelSlider1.left);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row you want to update.");
        }
        
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void btnBackRoomAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomAddActionPerformed
        tblRoom.clearSelection();
        jPanelSlider1.nextPanel(8, panelRoom, jPanelSlider1.right);
    }//GEN-LAST:event_btnBackRoomAddActionPerformed

    private void btnBackRoomUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomUpdateActionPerformed
        jPanelSlider1.nextPanel(8, panelRoom, jPanelSlider1.right);
    }//GEN-LAST:event_btnBackRoomUpdateActionPerformed

    private void btnUpdateReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReserActionPerformed
        int viewRow = tblRes.getSelectedRow();
        if(viewRow>=0){
            lblIdResUpdate.setText(String.valueOf(tblRes.getValueAt(viewRow, 0)));
            lblIdGuestResUpdate.setText(String.valueOf(tblRes.getValueAt(viewRow, 1)));
            lblSpecialOrderResUpdate.setText((String)tblRes.getValueAt(viewRow, 2));
            lblCheckInResUpdate.setText((String)tblRes.getValueAt(viewRow, 3));
            lblCheckOutResUpdate.setText((String)tblRes.getValueAt(viewRow, 4));
            lblPriceResUpdate.setText("IDR. " + String.valueOf(tblRes.getValueAt(viewRow, 5)));
            lblDiskonResUpdate.setText((String.valueOf(tblRes.getValueAt(viewRow, 6)))+" %");
            lblTotPriceResUpdate.setText("IDR. " + String.valueOf(tblRes.getValueAt(viewRow, 7)));
//            cbStatusResUpdate.setSelectedIndex(0);
            if(tblRes.getValueAt(viewRow, 8).toString().equalsIgnoreCase("unconfirmed")){
                cbStatusResUpdate.setSelectedIndex(0);
            } else {
                cbStatusResUpdate.setSelectedIndex(1);
            }
            jPanelSlider1.nextPanel(8, panelReservationUpdate, jPanelSlider1.left);
        } else {            
            JOptionPane.showMessageDialog(this, "Please select a row you want to update.");
        }
    }//GEN-LAST:event_btnUpdateReserActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controllerKamar.updateKamar();
        controllerKamar.isiTable();
        tblRoom.clearSelection();
        jPanelSlider1.nextPanel(8, panelRoom, jPanelSlider1.right);        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSubmitAddKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAddKamarActionPerformed
        controllerKamar.insertKamar();
        controllerKamar.isiTable();
        tblRoom.clearSelection();
        jPanelSlider1.nextPanel(8, panelRoom, jPanelSlider1.right);
    }//GEN-LAST:event_btnSubmitAddKamarActionPerformed

    private void btnBackReser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackReser1ActionPerformed
        jPanelSlider1.nextPanel(8, panelReservation, jPanelSlider1.right);
    }//GEN-LAST:event_btnBackReser1ActionPerformed

    private void btnUpdateSubmitResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSubmitResActionPerformed
        controllerReservasi.updateReservasi();
        controllerReservasi.isiTable();
        tblRes.clearSelection();
        jPanelSlider1.nextPanel(8, panelReservation, jPanelSlider1.right);
    }//GEN-LAST:event_btnUpdateSubmitResActionPerformed

    private void btnRefreshReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshReserActionPerformed
        controllerReservasi.isiTable();
    }//GEN-LAST:event_btnRefreshReserActionPerformed

    private void btnBackRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackRoomTypeActionPerformed

    private void btnUpdateRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateRoomTypeActionPerformed

    private void btnInsertRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertRoomTypeActionPerformed

    private void btnDeleteRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRoomTypeActionPerformed

    private void btnBackRoomTypeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomTypeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackRoomTypeAddActionPerformed

    private void btnSubmitAddTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAddTipeKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitAddTipeKamarActionPerformed

    private void btnBackRoomTypeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomTypeUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackRoomTypeUpdateActionPerformed

    private void btnSubmitUpdateTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitUpdateTipeKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitUpdateTipeKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackReser;
    private javax.swing.JButton btnBackReser1;
    private javax.swing.JButton btnBackRoom;
    private javax.swing.JButton btnBackRoomAdd;
    private javax.swing.JButton btnBackRoomType;
    private javax.swing.JButton btnBackRoomTypeAdd;
    private javax.swing.JButton btnBackRoomTypeUpdate;
    private javax.swing.JButton btnBackRoomUpdate;
    private javax.swing.JButton btnDeleteReser;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnDeleteRoomType;
    private javax.swing.JButton btnInsertRoom;
    private javax.swing.JButton btnInsertRoomType;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageReser;
    private javax.swing.JButton btnManageRoom;
    private javax.swing.JButton btnRefreshReser;
    private javax.swing.JButton btnReviewReports;
    private javax.swing.JButton btnSubmitAddKamar;
    private javax.swing.JButton btnSubmitAddTipeKamar;
    private javax.swing.JButton btnSubmitUpdateTipeKamar;
    private javax.swing.JButton btnUpdateReser;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.JButton btnUpdateRoomType;
    private javax.swing.JButton btnUpdateSubmitRes;
    private javax.swing.JComboBox<String> cbStatusKamarAdd;
    private javax.swing.JComboBox<String> cbStatusKamarUpdate;
    private javax.swing.JComboBox<String> cbStatusResUpdate;
    private javax.swing.JComboBox<String> cbTipeKamarAdd;
    private javax.swing.JComboBox<String> cbTipeKamarUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCheckInResUpdate;
    private javax.swing.JLabel lblCheckOutResUpdate;
    private javax.swing.JLabel lblDiskonResUpdate;
    private javax.swing.JLabel lblIdGuestResUpdate;
    private javax.swing.JLabel lblIdResUpdate;
    private javax.swing.JLabel lblPriceResUpdate;
    private javax.swing.JLabel lblSpecialOrderResUpdate;
    private javax.swing.JLabel lblTotPriceResUpdate;
    private usu.widget.Panel panel1;
    private usu.widget.Panel panel2;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private usu.widget.glass.PanelGlass panelGlass8;
    private usu.widget.glass.PanelGlass panelGlass9;
    private usu.widget.Panel panelIcon;
    private usu.widget.Panel panelIcon1;
    private usu.widget.Panel panelIcon2;
    private usu.widget.Panel panelLoginForm;
    private usu.widget.Panel panelReservation;
    private usu.widget.Panel panelReservationUpdate;
    private usu.widget.Panel panelRoom;
    private usu.widget.Panel panelRoomAdd;
    private usu.widget.Panel panelRoomType;
    private usu.widget.Panel panelRoomTypeAdd;
    private usu.widget.Panel panelRoomTypeUpdate;
    private usu.widget.Panel panelRoomUpdate;
    private usu.widget.Panel panelTabelReser;
    private usu.widget.Panel panelTabelRoom;
    private usu.widget.Panel panelTabelRoom1;
    private javax.swing.JSpinner spIdKamarAdd;
    private javax.swing.JSpinner spIdKamarUpdate;
    private javax.swing.JSpinner spIdTipeKamarAdd;
    private javax.swing.JSpinner spIdTipeKamarUpdate;
    private javax.swing.JSpinner spNoKamarAdd;
    private javax.swing.JSpinner spNoKamarUpdate;
    private javax.swing.JTable tblRes;
    private javax.swing.JTable tblRoom;
    private javax.swing.JTable tblRoomType;
    private javax.swing.JTextField tfHargaTipeKamarAdd;
    private javax.swing.JTextField tfHargaTipeKamarUpdate;
    private javax.swing.JTextField tfNamaTipeKamarAdd;
    private javax.swing.JTextField tfNamaTipeKamarUpdate;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
